config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  get 'followings/index'
  devise_for :users
  get 'posts/index'
  root to:'posts#home'
  resources :posts do
    resources :comments
    resources :likes
    
    member do
      get 'home'
    end
  end
  resources :users
  resources :relationships

  resources :messages, :only => [:create, :index]
  resources :rooms, :only => [:create, :show, :index]
  


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true 
  belongs_to :post  
  belongs_to :user  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  has_many :likes

  validates :post_text, presence: true 
  validates :image, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments , dependent: :destroy
         
         has_one_attached :avatar 
         has_one_attached :backimage

         has_many :likes, dependent:  :delete_all
         has_many :liked_posts, through: :likes, source: :post

         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

         has_many :messages, dependent: :destroy
         has_many :entries, dependent: :destroy
         



        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
    
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

  def already_liked?(post)                #ユーザーが投稿に対して、すでにいいねをしているのかどうかを判定
    self.likes.exists?(post_id: post.id)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @users = User.all
  end

  def show
    user = User.find(params[:id])
    @name = user.name
    @prefecture = user.prefecture
    @business_name = user.business_name
    @profile = user.profile


    @users = User.all

    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render "shared/header" %>
<div class="main">
<div class="users-main">
  <div class="users-list-wrapper">
    <h1 class="page-title">生産者の一覧ページ1</h1>
    <div class="red-line"></div>
      <div class="users_lists">
        <div class="users-list">
          <% @users.each do |user| %>
          <% if user.kind == "1" %>
          <div class="farmer-lists">
            <div class="user-kind"><% link_to user.kind %></div>
            <% if user.avatar.attached? %>
              <div class="user-avataer"><%= link_to image_tag(user.avatar, class: :profile__img), user_path(user.id) %></div>
            <% else %>
              <p><%= image_tag("default_user.png",class: "profile-image") %></p>
            <% end %>
            <div class="user-name"><%= link_to user.name, user_path(user.id), class: :card__user__name  %></div>
            <div class="user-predecture"><%= link_to user.prefecture, user_path(user.id), class: :card__user__text %></div>
            <div class="business-name"><%= link_to user.business_name, user_path(user.id), class: :card__user__text %></div>
            <div class="user-profile"><%= link_to user.profile, user_path(user.id), class: :card__user__text %></div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="users-list-end-btn">
    <%= link_to "トップページに戻る", root_path, class: 'top-btn' %>
  </div>
</div>
</div>
<%= render "shared/footer" %>

<h1>DMサンプルアプリ</h1>
<% if user_signed_in? %>
<h2>Hello <%= current_user.email %></h2>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.email %>さん</a></p>
  <hr>
  <% end %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "ユーザーを登録する", new_user_registration_path %>
  <br>
  <%= link_to "ログインする", new_user_session_path %>
<% end %>

app/views/users/new.html.erb
<%= render "shared/header" %>
  <div class="users-main">
    <div class="users-list-wrapper">
        <h1 class="page-title">料理人の一覧ページ</h1>
        <div class="red-line"></div>
      <div class="users-lists">
        <div class="users-list">
            <% @users.each do |user| %>
            <% if user.kind == "2" %>
              <div class="chef-lists">
              <% if user.avatar.attached? %>
                <li><%= link_to image_tag(user.avatar, class: :profile__img), user_path(user.id) %></li>
                <% else %>
                <p><%= image_tag("default_user.png",class: "profile-image") %></p>
                <% end %>
                <li><%= link_to user.name, user_path(user.id), class: :card__user__name %></li>
                <li><%= link_to user.prefecture, user_path(user.id), class: :card__user__text %></li>
                <li><%= link_to user.business_name, user_path(user.id), class: :card__user__text %></li>
                <li><%= link_to user.profile, user_path(user.id), class: :card__user__text %></li>
              </div>
            <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

<div class="users-list-end-btn">
  <%= link_to "トップページに戻る", root_path, class: 'top-btn' %>
</div>

<%= render "shared/footer" %>

<!--h1>DMサンプルアプリ</h1>
<% if user_signed_in? %>
<h2>Hello <%= current_user.email %></h2>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.email %>さん</a></p>
  <hr>
  <% end %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "ユーザーを登録する", new_user_registration_path %>
  <br>
  <%= link_to "ログインする", new_user_session_path %>
<% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="user-profile">
  <div class="profile-heading">
    <div class="main">
      <div class="inner">
        <div class="user__wrapper">

 
 <% if user_signed_in? %>
     <% if current_user.id == @user.id %>
      <div class="user-edit-btn">
        <li><%=  link_to 'プロフィールを編集する', edit_user_registration_path, class: 'edit-btn' %></li>
      </div>
    <% else %>
    <% end %>
  <% end %>

        <div class="user-page-header">
          <div class="user-background-img">
            <!--背景画像-->
            <div class="user-background-image">
              <% if @user.backimage.attached? %>
              <!-- 画像が登録されている場合の処理-->
                <p><%= image_tag @user.backimage ,class: "profile-iage" %></p>
              <% else %>
              <!--画像が登録されていない場合の処理-->

              <p><%= image_tag("cabbage.png", :size => "50x50") %></p>
              <% end %>
            </div>
          </div>
            <div class="user-main-image">
              <!--プロフィール画像-->
              <% if @user.backimage.attached? %>
              <div class="profile-image-wrapper">
                <%= image_tag @user.avatar ,class: "profile-image" %>
              </div>
              <% else %>
              <p><%= image_tag("default_user.png",class: "profile-image") %></p>
              <% end %>
            </div>
            <div class="user-name"><%= @name %></div>
            <div class="user-prefecture"><%= @prefecture %></div>
            <div class="user-business-name"><%= @business_name %></div>
          </div>
        </div>

        <div class="user-info">
          <div class="user-info-upper">
            <div class="user-image-square">
              <% if @user.backimage.attached? %>
              <div class="profile-image-wrapper">
                <%= image_tag @user.avatar ,class: "user-image" %>
              </div>
              <% else %>
              <p><%= image_tag("default_user.png",class: "profile-image") %></p>
              <% end %>
            </div>
            <div class="user-infos">
              <div class="main-business-name"><%= @business_name %></div>
              <div class="main-name"><%= @name %></div>
              <div class="main-prefecture"><%= @prefecture %></div>
              <div class="main-profile"><%= @profile %></div>
            </div>
          </div>
          <div class="message-send-btn">
            <%=  link_to 'メッセージを送る', root_path, class: 'send-btn' %>
          </div>
        </div>

        <div class="message-send-second-btn">
          <%=  link_to 'この生産者にメッセージを送る', root_path, class: 'send-second-btn' %>
        </div>
        
      

          
          <!--フォローボタン>

        <div class="follow-info">
          <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
                <%= hidden_field_tag :follow_id, @user.id %>
                <%= f.submit 'フォロー中', class: "followings-btn" %>
              <% end %>
            <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
                <%= hidden_field_tag :follow_id, @user.id %>
                <%= f.submit 'フォローする', class: "followers-btn" %>
              <% end %>
            <% end %>
          <% end %>
        </div>

        <div class="follow-counts">
          <div class="follow-count"><%=@user.followings.count %>フォロー</div>
          <div class="follow-count"><%=@user.followers.count %>フォロワー</div>
        </div>-->

          <!--ユーザー詳細情報
          <div class="user-info">
            <div class="table">
                <div class="user-info-list">
                  <div class="table__col1">名前</div>
                  <div class="table__col2"><%= @name %></div>
                </div>

                <div class="user-info-list">
                  <div class="table__col1">お住まい</div>
                  <div class="table__col2"><%= @prefecture %></div>
                </div>

                <div class="user-info-list">
                  <div class="table__col1">事業者名</div>
                  <div class="table__col2"><%= @business_name %></div>
                </div>

                <div class="user-info-list">
                  <div class="table__col1">プロフィール</div>
                  <div class="table__col3"><%= @profile %></div>
                </div>
            </div>
          </div>
          ユーザー詳細情報-->


        <!--DM機能-->
        <div class="message">
          <div class="message-main">
            <b class="dm-title">DM機能</b>
            <h1></h1>
            <!--<h2 class="dm-from-name"><%#= @user.name %>さんとのチャットはこちらから</h2>-->

            <% if @user.id == current_user.id %>
              <% else %>
                <% if @isRoom == true %>
                  <p><a href="/rooms/<%= @roomId %>">チャットへすすむ</a>
              <% else %>
                <%= form_for @room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, :value=> @user.id %>
                  <% end %>
                    <%= f.submit "チャットを始める" %>
                <% end %>
              <% end %>
            <% end %>

            <h1> </h1>
            <% if user_signed_in? %>
            
              <% else %>
            <% end %>

          </div>
        </div>
        <!--DM機能-->

      </div>
    </div>
  </div>



</div>

  <div class="posted-contents-wrapper">

    <div class="posted">
      <div class="user-owned-post">投稿一覧</div>
      <div class="posted-under-line"></div>
      <div class="red-line"></div>
      <h2 class="posted-user-contents"></h2>
        <div class="posted-user-content">
          <% @user.posts.each do |post| %>
            <div class="posted-img-text">
              <div class="posted-img">
                <%= link_to image_tag(post.image, class: :posts_image), post_path(post.id) %>
              </div>
              <div class="posted-text">
              <a href="/#/<%= post.id %>"><%= post.post_text %></a>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>

    <% if user_signed_in? %>
     <% if current_user.id == @user.id %>
      <div class="user-edit-btn">
        <li><%=  link_to 'プロフィールを編集する', edit_user_registration_path, class: 'edit-btn' %></li>
        <div class="home-btn">
          <%= link_to "トップページに戻る", root_path, class: 'top-btn' %>
        </div>
      </div>
    <% else %>
      <div class="home-btn">
        <%= link_to "トップページに戻る", root_path, class: 'top-btn' %>
      </div>
    <% end %>
  <% end %>

    <div class="message-send-second-btn">
      <%=  link_to 'この生産者にメッセージを送る', root_path, class: 'send-second-btn' %>
    </div>




      <div class="three-users-list">
          <p class="another-users-title">他の生産者をみる</p>
      </div>
      <div class="another-users">
        <div class="users-list-content">
            <% @users.each do |user| %>
            <% if user.kind == "1" %>
            <div class="farmer-lists">
              <div class="user-kind"><% link_to user.kind %></div>
              <% if user.avatar.attached? %>
              <div class="user-avataer">
              <%= link_to image_tag(user.avatar, class: :profile__img), user_path(user.id) %>
              </div>
              <% else %>
              <p><%= image_tag("default_user.png",class: "profile-image") %></p>
              <% end %>
              <div class="user-names"><%= link_to user.name, user_path(user.id), class: :card__user__name  %></div>
              <div class="user-predecture"><%= link_to user.prefecture, user_path(user.id), class: :card__user__text %></div>
              <div class="business-name"><%= link_to user.business_name, user_path(user.id), class: :card__user__text %></div>
              <div class="user-profile"><%= link_to user.profile, user_path(user.id), class: :card__user__text %></div>
            </div>
            <% end %>
            <% end %>
          </div>
      </div>


<%= render "shared/footer" %>





<!--<h1>ユーザー詳細</h1>

<h2><%= @user.email %></h2>

<% if @user.id == current_user.id %>

<% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>-->