config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  get 'followings/index'
  devise_for :users
  get 'posts/index'
  root to:'posts#home'
  resources :posts do
    resources :comments
    resources :likes
    
    member do
      get 'home'
    end
  end
  resources :users
  resources :relationships

  resources :messages, :only => [:create, :index]
  resources :rooms, :only => [:create, :show, :index]
  


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true 
  belongs_to :post  
  belongs_to :user  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  has_many :likes

  validates :post_text, presence: true 
  validates :image, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments , dependent: :destroy
         
         has_one_attached :avatar 
         has_one_attached :backimage

         has_many :likes, dependent:  :delete_all
         has_many :liked_posts, through: :likes, source: :post

         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

         has_many :messages, dependent: :destroy
         has_many :entries, dependent: :destroy
         



        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
    
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

  def already_liked?(post)                #ユーザーが投稿に対して、すでにいいねをしているのかどうかを判定
    self.likes.exists?(post_id: post.id)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :create, :edit, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new

    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
    unless current_user.id == @post.user.id
      redirect_to action: :index 
    end 
  end

  def update
    if post = Post.find(params[:id])
      post.update(post_params)
      redirect_to post_path (post.id), method: :get
    else
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def home
    @posts = Post.all
  end


  private

  def post_params
    params.require(:post).permit(:post_text, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<h2 class="page-heading">編集post</h2>

<%= form_with(model: @post, local: true) do |f| %>

  <div class="field">
    <%= f.label :post_text, "投稿内容" %><br />
    <%= f.text_field :post_text %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>
</div>

<%= render "shared/footer" %>

app/views/posts/home.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="top-main-contents">

    <!--
    <div class="heading-img">
      <div class="out">
        <img src="">
        <input type=radio name="slide" id="slide1">
        <input type=radio name="slide" id="slide2">
        <input type=radio name="slide" id="slide3">
        <input type=radio name="slide" id="slide4">
        <div class="in">
            <label for="slide1"><span></span><a href="#1"><%= link_to image_tag("farmcheflogo.jpg", class:"img"), "/posts" %></a></label>
            <label for="slide2"><span></span><a href="#2"><%= link_to image_tag("owned-media.png", class:"img"), "/posts" %></a></label>
            <label for="slide3"><span></span><a href="#3"><%= link_to image_tag("post-view.png", class:"img"), "/posts" %></a></label>
            <label for="slide4"><span></span><a href="#4"><%= link_to image_tag("post-view.png", class:"img"), "/users" %></a></label>
        </div>
      </div>
    </div>
    -->
    
    <div class="service-massages">

      <div class="header-ber-lists">
        <ul class="show-lists hidden" id="pull-down">
          <li>リスト1</li>
          <li>リスト2</li>
          <li>リスト3</li>
          <li>リスト4</li>
        </ul>
      </div>
      <div class="service-massage">
        <%= link_to image_tag("top-img.png", class:"yagi-kike-img"), "/" %>

      
      <div class="arrow-area">
        <%#= link_to image_tag("yellow_grass.png", class:"yellow-grass-img"), "/" %>
      </div>
    </div>

    <div class="appeal-point">
      <%= link_to image_tag("3hair-yellow.png", class:"hair-yellow"), "/" %>
      <div class="about-service">
        <h1 class="service-title">Farmer Chefとは？</h1>
        <p class="service-description-min">湘南・西湘の生産者と料理人が、想いで繋がることができるプラットフォームです。取り引き先という関係を超えて、その地域の「美味しい」を守り、一緒に創り上げる仲間と出会えます。</p>
      </div>
    </div>

    <div class="concep-message">
          <div class="farm-chef-ex">
            <%= link_to image_tag("people-comming-hiratuka.png", class:"farm-chef-ex-img"), "/" %>
          </div>
    </div>

    <div class="service-can-do">
      <%= link_to image_tag("3hair-yellow.png", class:"hair-yellow"), "/" %>
      <div class="about-service">
          <h1 class="service-title">Farmer Chefにできること</h1>
      </div>

      <div class=first-step-content>
        <div class=step>
          <%= link_to image_tag("step1.jpg", class:"first-step-img"), "/" %>
        </div>
        <div class=text-p>
          <b class="service-description-step">生産者と料理人がつながること</b>
          <div class="under-line"></div>
          <p class="service-description-step">農家さんと料理人さんの共通の悩み、お互いをもっと知りたい！をサポートするサービス、それが「ファーマーシェフ」です。</p>
        </div>
      </div>

      <div class=second-step-content>
        <div class=text-p>
          <b class="service-description-step-sec">その地域の「美味しい」を一緒に作る</b>
          <div class="under-line-yellow"></div>
          <p class="service-description-step-sec">ファーマーシェフでピッタリな相手を見つけたら「おいしい」を一緒につくる第一歩、さっそくメッセージを送ります。</p>
        </div>
        <div class=step>
          <%= link_to image_tag("make-with-good.png", class:"make-with-good"), "/" %>
        </div>
      </div>
    </div>

    <div class=third-step-content>
      <div class=step>
        <%= link_to image_tag("with-future.png", class:"with-future"), "/" %>
      </div>
      <div class=text-p>
        <b class="service-description-step">未来を共に描く</b>
        <div class="under-line"></div>
        <p class="service-description-step">出会いを通じて誕生したお料理は特別な一品に。ファーマーシェフをきっかけに想いを共有する「仲間」を増やし、コミュニティを広げていきましょう。</p>
      </div>
    </div>

    <div class="howto-use">
          <div class="use-service">
            <%= link_to image_tag("howto-use.png", class:"howto-use-service"), "/" %>
          </div>
    </div>

    <div class="search-users">
      <div class="search-user">

        <div class="user-box-left">
          <div class="search-user-garlic-img">
            <%= link_to image_tag("garlic-and-basil.png", class:"service-massage-img"), "/" %>
            <div class="search-content">
              <p class="user-description">多様な生産者と繋がることができる。季節や地域の美味しさを味わう人へ。 様々な食材とであえます。</p>
              <div class="user-box-btn">
                <%= link_to "料理人を探す", new_user_path, class: 'test-btn3' %>
              </div>
            </div>
          </div>
        </div>

        <div class="user-box-right">
          <div class="search-user-calotte-img">
            <%= link_to image_tag("calotte.png", class:"service-massage-img"), "/" %>
            <div class="search-content">
              <p class="user-description">新しい顧客を見つけられる。規格外の野菜を売ることが可能になります。</p>
              <div class="user-box-btn">
                <%= link_to "生産者を探す", users_path, class: 'test-btn3' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="service-description">
      <b class="service-description-title">※みんなの投稿を促すメッセージを追加</b>
    </div>

    <div class="home-posts">
      <div class="card__wrapper_img">
        <h1 class="page-title" >みんなの投稿</h1>
        <div class="red-line"></div>
          <div class="card-main">
            <div class="posts-list-top">
              <% @posts.each do |post| %>

                <div class="card-contents-lists-top">

                  <div class="card-img-wrapper">
                    <div class="card-img-top">
                      <%= link_to image_tag(post.image, class: :card__img__top), post_path(post.id) %>
                    </div>
                  </div>

                  <div class="card-content-top">
                    <div class="postuser-img-name-date">
                      <div class="post-date-top">
                        <p><%= post.created_at.strftime('%Y/%m/%d') %> </p>
                      </div>
                      <div class="postuser-img-top">
 
                      <div class="postuser-name-top">
                          <%= link_to "#{post.user.name}", user_path(post.user.id), class: :card__user__top %>
                      </div>
                    </div>

                    <div class="card-text-top">
                      <%= link_to post.post_text, post_path(post.id), class: :card__text__top %>
                    </div>
                    <div class="like-count">
                       いいね! <%= post.likes.count %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="top-page-posts-btn">
      <%= link_to "全ての投稿を見る", posts_path, class: 'test-btn3' %>
    </div>



    <div class="media-img">
      <%= link_to image_tag("media-list.png", class:"media-list-img"), "/" %>
    </div>
  </div>
</div>










<%= render "shared/footer" %>2

app/views/posts/index.html.erb
<%= render "shared/header" %>


<div class="main">
  <div class="posts-list">
      <div class="users-posts-image">
        <%= link_to image_tag("users-posts.png", class:"yagi-kike-img"), "/" %>
        <div class="page-massage">
        <%= link_to image_tag("post-page-massage.png", class:"page-massage-bk") %>
        <p class="post-top-text">生産者・料理人がそれぞれ伝えたいことを投稿していきます。 余ってしまった野菜の告知や、求めている食材が見つからない場合、 こちらで投稿することでより多くの方と繋がれる可能性が産まれます。</p>
      </div>
  </div>

  <h1 class="all-post" >全ての投稿</h1>
  <div class="card__wrapper">
      <div class="red-line"></div>
        <div class="card-main">
          <div class="posts-list">
            <% @posts.each do |post| %>
              <div class="card-contents">
                <div class="card-content">
                  <div class="postuser-img-name-date">

                      <div class="post-header">
                        <div class="post-header-left">
                          <% if post.user.avatar.attached? %>
                            <div class="postuser-img">
                              <%=link_to image_tag(post.user.avatar, class: :card__im) %>
                            </div>
                          <% else %>
                            <p><%= image_tag("default_user.png",class: :card__im) %></p>
                          <% end %>
                        </div>
                        <div class="post-header-right">
                          <div class="postuser-name">
                            <%= link_to "#{post.user.name}さんが投稿しました。", user_path(post.user.id), class: :card__user %>
                          </div>
                          <div class="post-data">
                            <p><%= post.created_at.strftime('%Y/%m/%d') %> </p>
                          </div>
                        </div>
                      </div>

                      <div class="card-img-wrapper">
                        <div class="card-text">
                          <%= link_to post.post_text, post_path(post.id), class: :card__user %>
                        </div>
                        <div class="card-img">
                          <%= link_to image_tag(post.image, class: :card__img), post_path(post.id) %>
                        </div>
                      </div>

                      <div class="post-footer">
                        <div class="like-count">
                          いいね！ <%= post.likes.count %>
                        </div>

                        <div class="comments-count">
                          コメント <%= post.comments.count %>
                        </div>
                      </div>

                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>


  <div class="new-post">
    <li><%= link_to '新規POST', new_post_path, class: :post__btn %></li>
  </div>
    <li><%= link_to 'ユーザーの一覧', users_path %></li>
</div>


<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>


<div class="main">
  <div class="posts-list">
      <div class="users-posts-image">
        <%= link_to image_tag("new-postpage.png", class:"yagi-kike-img") %>
      </div>
  </div>

  <div class="post-main">
    <div class="red-line"></div>
    <%= form_with(model: @post, local: true) do |f| %>

    <div class="field-image">
      <div class="image-select-left">
        <%= link_to image_tag("image-select.png", class:"image-select-img") %>
        <%= f.label :image, "画像を選択", class:"post-image-label" %><br />
      </div>
      <div class="image-select-right">
        <%= f.file_field :image, class:"post-image"%>
      </div>
    </div>

    <div class="post-text-field">
      <div class="post-content-top">
        <%= link_to image_tag("pen.png", class:"pen-img") %>
        <p class="image-label">投稿内容</p>
      </div>
        <%= f.text_field :post_text, class:"post-text" %>
    </div>

    <div class="actions">
      <%= f.submit "投稿する", class: :form__btn  %>
    </div>

    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post-container">
  <div class="top-page-posts-btn">
    <%= link_to "投稿一覧", posts_path, class: 'user-btn' %>
  </div>
  <h1 class="page-title" >詳細ページ</h1>
    <div class="red-line"></div>
<% if user_signed_in? && current_user.id == @post.user_id %>
      
        <div class="post__manage">
          <%= link_to "編集する",  edit_post_path, class: :post__btn %>
          <%= link_to "削除する",  post_path, method: :delete, class: :post__btn %>
        </div>
<% end %>

<div class="post-content-show">
  <div class="post-body">
    <div class="post__user__name">
      <%= link_to @post.user.name , user_path, class: :hoge %>
    </div>
    <p><%= @post.created_at %> </p>
    <div class="post__detail">
      <%= image_tag @post.image,class: "profile-image" %>
    </div>
    <div class="post__text">
      <%=  @post.post_text %>
    </div>
  </div>
</div>


<%= form_with model: [@post, @comment], local: true do |f|%>
    <div class="field-comment">
      <%= f.label :comment_text, "コメント" %><br />
      <%= f.text_field :comment_text %>
    </div>
    <div class="actions">
      <%= f.submit "送信する", class: :form__btn %>
    </div>
<% end %>


  <div class="comment-lists">
    <% @comments.each do |comment| %>

      <p class="comment_text_area">
        <%= comment.comment_text %>
      </p>
      <p class="comment_user_area">
        <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %>
      </p>
    <% end %>
  </div>
</div>

<div class="like-btn">
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post),class: :like_btn, method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>
</div>


<%= render "shared/footer" %>