config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  get 'followings/index'
  devise_for :users
  get 'posts/index'
  root to:'posts#home'
  resources :posts do
    resources :comments
    resources :likes
    
    member do
      get 'home'
    end
  end
  resources :users
  resources :relationships

  resources :messages, :only => [:create, :index]
  resources :rooms, :only => [:create, :show, :index]
  


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true 
  belongs_to :post  
  belongs_to :user  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  has_many :likes

  validates :post_text, presence: true 
  validates :image, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments , dependent: :destroy
         
         has_one_attached :avatar 
         has_one_attached :backimage

         has_many :likes, dependent:  :delete_all
         has_many :liked_posts, through: :likes, source: :post

         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

         has_many :messages, dependent: :destroy
         has_many :entries, dependent: :destroy
         



        def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
    
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

  def already_liked?(post)                #ユーザーが投稿に対して、すでにいいねをしているのかどうかを判定
    self.likes.exists?(post_id: post.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="main">
<div class="share-footer">
  <div class="contents">

    <div class="contet">
      <div class="content-buy">
        <b>購入したい</b>
      </div>
      <div class="buy-lists">
        <li>farm-chef</li>
        <li>食品基準</li>
        <li>ご利用ガイド</li>
        <li>品質保証</li>
        <li>飲食店</li>
        <li>イベント主催</li>
      </div>
    </div>

    <div class="contet">
      <div class="content-buy">
        <b>出品したい</b>
      </div>
      <div class="buy-lists">
        <li>出品者募集</li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </div>
    </div>

    <div class="contet">
      <div class="content-buy">
        <b>farm-chefについて</b>
      </div>
      <div class="buy-lists">
        <li>運営会社f</li>
        <li>よくある質問</li>
        <li>お問い合わせ</li>
        <li>利用規約</li>
        <li>プライバシー</li>
        <li>特定商取引</li>
      </div>
    </div>

    <div class="contet">
      <div class="content-buy">
        <b>その他</b>
      </div>
      <div class="buy-lists">
        <li>farm-chef</li>
        <li>farm-chefマガジン</li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </div>
    </div>


    
  </div>
</div>
</div>

app/views/shared/_header.html.erb
<div class="main">
<div class="share-header">
  <div class="header-logo">
    <%= link_to image_tag("farm-chef-logo.png", class:"farm-chef-icon"), "/" %>
  </div>
  <div class='search-bar-contents'>
    <form class="search-form" action="#">
        <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button" >検索</button>
    </form>
  </div>

<div class="user-bar">
  <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
    <div class="my-profile-area" id="lists">


      <div class="profile-icon">
        <%= link_to image_tag("profile-icon-img.png", class:"profile-icon"), "/" %>
      </div>

      <div class="greeting"> 
        <%= link_to "マイページ", "/users/#{current_user.id}", class: :hoge%>
      </div>
    </div> 
    <% else %>
  <%# // ログインしているときは上記を表示する %>
    <% end %>

  <div class="user-status">
    <% if user_signed_in? %>
      <div class="profile-icon" >
        <%= link_to image_tag("logout-img.png", class:"profile-icon"), "/" %>
      </div>
      <div class="user-status-info" >
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%></li>
      </div>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to '新規登録', new_user_registration_path %></li>
    <% end %>
  </div>
</div>

  


</div>
</div>



  <!--<div class="messages-admin-list">
    <b>管理者ツール</b>
    <li><%#= link_to '管理者ページ', messages_path %></li>
  </div>-->

<!--<header>
  <nav>
    <ul>
      <%# if user_signed_in? %>
        <li>ユーザー</li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <%# elsif admin_signed_in? %>
        <li>管理者</li>
        <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      <%# else %>
        <li>ゲストユーザー</li>
        <li><%= link_to '管理者ページ', "/admins/sign_in/" %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <%# end %>
    </ul>
  </nav>
</header>-->

 <!-- ############ ヘッダー ########### -->